### ISSUE TITLE
Add C wrapper

### ISSUE THREAD

**Issue by dlfivefifty** [MikaelSlevinsky/FastTransforms.jl#1]
I think other people might find the transforms useful in C and Python code.  I think it's easy to wrap the Julia code in a C library:

http://docs.julialang.org/en/release-0.4/manual/embedding/

Down the line (0.5?) it will be possible to compile Julia code to a library that doesn't depend on an Julia installation.

**Comment by MikaelSlevinsky** [comment]
I think it's going to be the other way around: https://github.com/MikaelSlevinsky/FastTransforms. Once I get a makefile working that builds on most common Julia platforms, then 2D elements of this package will be the wrappers.
