### ISSUE TITLE
Move pochhammer to SpecialFunctions.jl?

### ISSUE THREAD

**Issue by dlfivefifty** [MikaelSlevinsky/FastTransforms.jl#14]

**Comment by MikaelSlevinsky** [comment]
The Lambda function could be moved at the same time.

**Comment by MikaelSlevinsky** [comment]
There's also the sine and cosine integrals here https://github.com/MikaelSlevinsky/SincFun.jl/blob/master/src/sinc.jl

**Comment by dlfivefifty** [comment]
I don't think Lambda is standard enough

**Comment by MikaelSlevinsky** [comment]
If people need a specialized Pochhammer symbol, then they should be using a ratio of Stirling's approximations. I have this implemented and have used it successfully on a case-by-case basis, cancelling common terms for best accuracy and efficiency.
