### ISSUE TITLE
Coverage?

### ISSUE THREAD

**Issue by kshyatt** [MikaelSlevinsky/FastTransforms.jl#18]
This looks like a really great package. You have a great README and tests - I was wondering if you upload coverage statistics and if so, would you be willing to put a badge on your README?

Cheers,
Katharine

**Comment by MikaelSlevinsky** [comment]
Thank you! I can try uploading coverage, but if it's embarrassingly low I might have to turn it off.

**Comment by kshyatt** [comment]
Well, I happen to be in the market for a package to write some tests for 😉

**Comment by MikaelSlevinsky** [comment]
I guess it's 84%. "Not bad, I've seen a lot worse."
