### ISSUE TITLE
add femtocleaner bot

### ISSUE THREAD

**Issue by dlfivefifty** [MikaelSlevinsky/FastTransforms.jl#26]
femtocleaner https://github.com/JuliaComputing/FemtoCleaner.jl updates deprecated syntax automatically via a pull request.

**Comment by MikaelSlevinsky** [comment]
done

**Comment by dlfivefifty** [comment]
Great! When you are ready to drop 0.5 support (and add 0.7 support), just push a new REQUIRE and it should automatically make a pull request.
