### ISSUE TITLE
Run femtocleaner

### ISSUE THREAD

**Issue by dlfivefifty** [MikaelSlevinsky/FastTransforms.jl#29]

**Comment by MikaelSlevinsky** [comment]
How do I run it?

<img width="1440" alt="screen shot 2017-11-13 at 6 24 19 pm" src="https://user-images.githubusercontent.com/8176037/32756509-13edd734-c8a0-11e7-8447-b8d3d95935a9.png">

<img width="1438" alt="screen shot 2017-11-13 at 6 24 04 pm" src="https://user-images.githubusercontent.com/8176037/32756516-17eb0de8-c8a0-11e7-8a54-b98ba43e7984.png">

**Comment by dlfivefifty** [comment]
It said just open an issue called “Run femtobot”, but that didn’t seem to do anything

**Comment by MikaelSlevinsky** [comment]
Oh I see. Maybe it has to be an owner?
