### ISSUE TITLE
Incremental compilation broken

### ISSUE THREAD

**Issue by dpsanders** [MikaelSlevinsky/FastTransforms.jl#33]
With a fresh install of the released version on Julia 0.6.2:

```
julia> using FastTransforms
INFO: Precompiling module FastTransforms.
WARNING: --output requested, but no modules defined during run
WARNING: The call to compilecache failed to create a usable precompiled cache file for module FFTW. Got:
WARNING: Cache file "/Users/dpsanders/.julia/lib/v0.6/FFTW.ji" not found.
WARNING: eval from module Main to ToeplitzMatrices:
Expr(:call, Expr(:., :Base, :include_from_node1)::Any, "/Users/dpsanders/.julia/v0.6/FFTW/src/FFTW.jl")::Any
  ** incremental compilation may be broken for this module **

WARNING: --output requested, but no modules defined during run
WARNING: The call to compilecache failed to create a usable precompiled cache file for module FFTW. Got:
WARNING: Cache file "/Users/dpsanders/.julia/lib/v0.6/FFTW.ji" not found.
WARNING: eval from module Main to LowRankApprox:
Expr(:call, Expr(:., :Base, :include_from_node1)::Any, "/Users/dpsanders/.julia/v0.6/FFTW/src/FFTW.jl")::Any
  ** incremental compilation may be broken for this module **
```

**Comment by MikaelSlevinsky** [comment]
I've seen this before; can it be ignored? (Is that an FFTW.jl on 0.6 issue?)

Cheers,

Mikael

On Feb 20, 2018, at 1:06 PM, David P. Sanders <notifications@github.com<mailto:notifications@github.com>> wrote:


With a fresh install of the released version on Julia 0.6.2:

julia> using FastTransforms
INFO: Precompiling module FastTransforms.
WARNING: --output requested, but no modules defined during run
WARNING: The call to compilecache failed to create a usable precompiled cache file for module FFTW. Got:
WARNING: Cache file "/Users/dpsanders/.julia/lib/v0.6/FFTW.ji" not found.
WARNING: eval from module Main to ToeplitzMatrices:
Expr(:call, Expr(:., :Base, :include_from_node1)::Any, "/Users/dpsanders/.julia/v0.6/FFTW/src/FFTW.jl")::Any
  ** incremental compilation may be broken for this module **

WARNING: --output requested, but no modules defined during run
WARNING: The call to compilecache failed to create a usable precompiled cache file for module FFTW. Got:
WARNING: Cache file "/Users/dpsanders/.julia/lib/v0.6/FFTW.ji" not found.
WARNING: eval from module Main to LowRankApprox:
Expr(:call, Expr(:., :Base, :include_from_node1)::Any, "/Users/dpsanders/.julia/v0.6/FFTW/src/FFTW.jl")::Any
  ** incremental compilation may be broken for this module **

**Comment by dlfivefifty** [comment]
I fixed this in a few packages by only loading FFTW.jl in Julia v0.7, otherwise use Base.FFTW

**Comment by MikaelSlevinsky** [comment]
Oh I think you already fixed this on master. Maybe all it needs is a new tag.

Cheers,

Mikael

On Feb 20, 2018, at 1:36 PM, Sheehan Olver <notifications@github.com<mailto:notifications@github.com>> wrote:


I fixed this in a few packages by only loading FFTW.jl in Julia v0.7, otherwise use Base.FFTW

**Comment by MikaelSlevinsky** [comment]
Should be fixed with the new tag.
