### ISSUE TITLE
Too-specific typing for `fft`

### ISSUE THREAD

**Issue by dpsanders** [MikaelSlevinsky/FastTransforms.jl#34]
The types for the `fft` functions seem to be overly specific. 
(It looks like they should work for any `Real`.)
Is this deliberate or should I loosen them?

**Comment by MikaelSlevinsky** [comment]
I think the BigFloat FFT is only meant to be a patch until professional FFT writers introduce them in, say, `AbstractFFTs.jl`.

**Comment by dpsanders** [comment]
Understood, but in the mean time it would be useful to have them.

**Comment by dlfivefifty** [comment]
Probably it should be redisgned to define these for a new function ` FastTransforms.fft ` , instead of ` Base.fft ` .

And a PR should be made moving these  into AbstractFFTs.jl

**Comment by MikaelSlevinsky** [comment]
Closed by #64
