### ISSUE TITLE
SphereFun transform?

### ISSUE THREAD

**Issue by dlfivefifty** [MikaelSlevinsky/FastTransforms.jl#36]
Is there a transform from a grid to the basis expected in `fourier2ph`?

I can use 2D Fourier and drop coefficients, but that seems wasteful.

**Comment by MikaelSlevinsky** [comment]
https://github.com/MikaelSlevinsky/FastTransforms.jl/blob/master/src/SphericalHarmonics/synthesisanalysis.jl

https://github.com/MikaelSlevinsky/FastTransforms.jl/blob/master/test/sphericalharmonics/synthesisanalysistests.jl

**Comment by MikaelSlevinsky** [comment]
Also, see the function `evaluate_nonlinear_operator!`:

https://github.com/JuliaApproximation/SpectralTimeStepping.jl/blob/master/NonlocalSphere/SLPDE.jl
