### ISSUE TITLE
Confusion between real and complex-valued SH and double Fourier

### ISSUE THREAD

**Issue by dlfivefifty** [MikaelSlevinsky/FastTransforms.jl#40]
The docs suggest that `sph2fourier` and `fourier2sph` are for complex-valued bases, but it looks like it's actual real-valued bases.  This was our quick hack to convert to complex-valued SH:
```julia
function function2sph(f, n)
    n = 20
    θ = (0.5:n-0.5)/n * π
    φ = (0:2n-2)*2/(2n-1) * π
    F = [f(θ,φ) for θ in θ, φ in φ]
    V = zero(F)
    A_mul_B!(V, FastTransforms.plan_analysis(F), F)
    M = size(V,2)
    P = eye(Complex128,M)
    for k = 2:4:M
        P[k:k+1,k:k+1] = [im im;
                      -1 1]/sqrt(2)
      end
     # fix weird sign
      for k = 4:4:M
          P[k:k+1,k:k+1] = [-im im;
                        1 1]/sqrt(2)
        end
        (V |> fourier2sph)          * P
end
```

**Comment by MikaelSlevinsky** [comment]
Yep, the bases are real, otherwise the data are doubled (and hermiticity is annoying to keep track of, and is subject to tolerances in numerics).

Probably the hack shouldn't use a dense matrix-matrix product since P is tridiagonal.

**Comment by dlfivefifty** [comment]
Ok the docs incorrectly say that it is the complex transform

Though I think sph2fourier and fourier2sph are exactly the same for both complex/real valued cases

**Comment by MikaelSlevinsky** [comment]
Yes I agree the docs should be fixed

**Comment by MikaelSlevinsky** [comment]
> Though I think sph2fourier and fourier2sph are exactly the same for both complex/real valued cases

That's right, the row basis is independent of the column transforms.
