### ISSUE TITLE
cheb2tri: why sqrt(2π)?

### ISSUE THREAD

**Issue by dlfivefifty** [MikaelSlevinsky/FastTransforms.jl#49]
```julia
F = zeros(10,10)
    F[1,1] = 1

F̃ = cheb2tri(F, -0.0, -0.5, -0.5)
F̃[1,1] ≈ sqrt(2π) # My oh my...why? 
```

**Comment by MikaelSlevinsky** [comment]
The convention in this repository is that total degree polynomial bases (spherical/triangular/disk [in the future] harmonics) are L<sup>2</sup> orthonormalized. See the triangle transform example for further details

https://github.com/MikaelSlevinsky/FastTransforms.jl/blob/master/examples/triangle.jl
