### ISSUE TITLE
NFFT and INFFT

### ISSUE THREAD

**Issue by ajt60gaibb** [MikaelSlevinsky/FastTransforms.jl#5]
Any interest in having a nonuniform fast Fourier transform (FFT) and inverse NFFT in `FastTransforms.jl`?  I have one implemented, but it is not based on asymptotic expansions.

**Comment by MikaelSlevinsky** [comment]
Yes of course! And also ndct's and ndst's to enable the discrete Legendre transform.

Cheers,

Mikael

**Comment by ajt60gaibb** [comment]
I added a branch: 
https://github.com/MikaelSlevinsky/FastTransforms.jl/tree/add-nonuniformFFT
that implements the most basic version of the nonuniform FFT.  

Things to do: 
1) Plan FFTs, 
2) Add support for `BigFloats`.  The parameter `18` needs to be selected as `eps` dependent.

**Comment by MikaelSlevinsky** [comment]
ToeplitzMatrices.jl now has its own `gc`, so maybe avoid requiring IterativeLinearSolvers.jl?

**Comment by ajt60gaibb** [comment]
Should we code up my own conjugate gradient algorithm, then?

**Comment by MikaelSlevinsky** [comment]
A submodule has been added to ToeplitzMatrices.jl [here](https://github.com/andreasnoack/ToeplitzMatrices.jl/blob/master/src/iterativeLinearSolvers.jl) containing `cg`. Since we already require ToeplitzMatrices.jl, can this be used?

**Comment by MikaelSlevinsky** [comment]
Oh, but it says eventually will use IterativeLinearSolvers again.
