### ISSUE TITLE
Sphevaluate Bug

### ISSUE THREAD

**Issue by Kathryn-Drake** [MikaelSlevinsky/FastTransforms.jl#55]
When using the sphevaluate function for the first time in a session, the result is incorrect. However, every subsequent time the function is used, the correct result is returned. 
Below is a snippet of code that reproduces this issue. 
I am using Julia version 0.6.2.
```
julia> using FastTransforms

julia> Pkg.status("FastTransforms")
 - FastTransforms                0.3.0

julia> sphevaluate(0,0,0,0)
0.0209479177387814 + 0.0im

julia> sphevaluate(0,0,0,0)
0.28209479177387814 + 0.0im
```

**Comment by dlfivefifty** [comment]
Does the initial value change when you rerun it in a fresh session? (On the surface sounds like uninitialzed memory.)

**Comment by MikaelSlevinsky** [comment]
Interesting bug!

Note that the convention has changed (i.e. `sphevaluate` is real orthonormal from this commit https://github.com/MikaelSlevinsky/FastTransforms.jl/commit/18ba6ce37753c8883f3cc0de208a433ad1792919 onward).

**Comment by Kathryn-Drake** [comment]
No, it is the same (incorrect) initial value after every new session. My advisor also had the same results on his machine.
After reading your comment, I ran the following lines. 
```
julia> using FastTransforms

julia> c=sphevaluate(0,0,0,0)
0.0209479177387814 + 0.0im

julia> c
0.28209479177387814 + 0.0im
```
It seems to be assigning the correct value, at least.

**Comment by dlfivefifty** [comment]
What machines? On a mac I get 
```julia

julia> using FastTransforms
[ Info: Recompiling stale cache file /Users/solver/.julia/compiled/v1.0/FastTransforms/5Lm8s.ji for FastTransforms [057dd010-8810-581a-b7be-e3fc3b93f78c]

julia> c=sphevaluate(0,0,0,0)
0.28209479177387814
```

**Comment by MikaelSlevinsky** [comment]
Could it be a floating-point display bug? The digits seem way too similar

**Comment by dlfivefifty** [comment]
First: why is it complex and mine is real?

**Comment by MikaelSlevinsky** [comment]
@dlfivefifty The convention change from 18ba6ce onward. See #40.

**Comment by dlfivefifty** [comment]
OK so I'm more up to date? (Must be: I'm on master..) @Kathryn-Drake Can try again on master?

**Comment by Kathryn-Drake** [comment]
I ran Pkg.update() before submitting this issue. Would this not pull the updates for FastTransforms?

**Comment by dlfivefifty** [comment]
That pulls the last tagged version, which lags behind master. I think `Pkg.develop("FastTransforms")` will pull master.

**Comment by MikaelSlevinsky** [comment]
I don't have 0.6.2, but I do have an old copy of 0.6.4 and (at least on macOS) the bug is gone
```julia
Last login: Fri Oct 12 09:34:23 on ttys001
sec-12-1681:~ Mikael$ exec '/Applications/Julia-0.6.app/Contents/Resources/julia/bin/julia'
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.4 (2018-07-09 19:09 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin14.5.0

julia> using FastTransforms

julia> sphevaluate(0,0,0,0)
0.28209479177387814

julia> sphevaluate(0,0,0,0)
0.28209479177387814

```

**Comment by Kathryn-Drake** [comment]
Thank you for your responses; the bug is indeed fixed in the updated versions.
